# PORT: 8089
APISERVER: https://freechat.xyhelper.cn/backend-api/conversation
PASSMODE: true
MAXTIME: 60
NOPLUGINS: true
KEEPHISTORY: true


sk-api-xyhelper-cn-free-token-for-everyone-xyhelper: "xyhelper.cn"
